org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:\\Users\\valba\\AppData\\Roaming\\PrismLauncher\\java\\java-runtime-epsilon
# Fabric (cibles fixes demandées : Minecraft 26.1.2 / Loader 0.19.3)
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.18-SNAPSHOT
# Dernière build Fabric API publiée pour 26.1.2 sur maven.fabricmc.net
fabric_api_version=0.155.3+26.1.2

# Mod
version=0.1.0
group=com.valafre
archives_base_name=automod
